import { useState, useEffect } from "react";
import API from "../../api/axios";
import Navbar from "../../components/Navbar";

const MedicalRecords = () => {
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [expanded, setExpanded] = useState(null);

  const handlePrint = (record) => {
  const win = window.open("", "_blank");
  win.document.write(`
    <html>
      <head>
        <title>Medical Record — ${record.diagnosis}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
          h1 { color: #1a237e; font-size: 22px; margin-bottom: 4px; }
          .subtitle { color: #888; font-size: 14px; margin-bottom: 30px; }
          .section { margin-bottom: 20px; }
          .label { font-size: 11px; text-transform: uppercase; color: #aaa;
                   letter-spacing: 0.05em; margin-bottom: 4px; font-weight: 700; }
          .value { font-size: 15px; font-weight: 500; }
          .notes { background: #fffde7; border-left: 3px solid #f9a825;
                   padding: 12px; border-radius: 4px; font-size: 14px;
                   line-height: 1.6; }
          .footer { margin-top: 40px; font-size: 12px; color: #aaa;
                    border-top: 1px solid #eee; padding-top: 16px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>DoCare — Medical Record</h1>
        <div class="subtitle">Official medical record document</div>
        <div class="section">
          <div class="label">Diagnosis</div>
          <div class="value">${record.diagnosis}</div>
        </div>
        <div class="section">
          <div class="label">Doctor</div>
          <div class="value">Dr. ${record.doctor?.name || "Unknown"}</div>
        </div>
        <div class="section">
          <div class="label">Visit date</div>
          <div class="value">${new Date(record.visitDate).toLocaleDateString("en-US", {
            weekday: "long", year: "numeric", month: "long", day: "numeric"
          })}</div>
        </div>
        ${record.notes ? `
        <div class="section">
          <div class="label">Doctor notes</div>
          <div class="notes">${record.notes}</div>
        </div>` : ""}
        <div class="footer">
          Generated by DoCare Hospital Document Management System · ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `);
  win.document.close();
  win.print();
};

  useEffect(() => {
    const fetchRecords = async () => {
      try {
        const { data } = await API.get("/records/my");
        setRecords(data);
      } catch (err) {
        setError("Failed to load medical records");
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecords();
  }, []);

  if (loading) return (
    <div>
      <Navbar />
      <div style={styles.center}>Loading medical records...</div>
    </div>
  );

  return (
    <div style={styles.page}>
      <Navbar />
      <div style={styles.container}>
        <div style={styles.header}>
          <h2 style={styles.title}>Medical Records</h2>
          <p style={styles.sub}>{records.length} record{records.length !== 1 ? "s" : ""} found</p>
        </div>

        {error && <div style={styles.error}>{error}</div>}

        {records.length === 0 ? (
          <div style={styles.emptyState}>
            <div style={styles.emptyIcon}>🏥</div>
            <div style={styles.emptyTitle}>No medical records yet</div>
            <div style={styles.emptySub}>Your doctor will add records after your visits</div>
          </div>
        ) : (
          <div style={styles.list}>
            {records.map((r) => (
              <div key={r._id} style={styles.card}>
                <div
                  style={styles.cardHeader}
                  onClick={() => setExpanded(expanded === r._id ? null : r._id)}
                >
                  <div style={styles.cardLeft}>
                    <div style={styles.diagnosisLabel}>Diagnosis</div>
                    <div style={styles.diagnosis}>{r.diagnosis}</div>
                    <div style={styles.meta}>
                      Dr. {r.doctor?.name || "Unknown"} —{" "}
                      {new Date(r.visitDate).toLocaleDateString("en-US", {
                        year: "numeric", month: "long", day: "numeric"
                      })}
                    </div>
                  </div>
                  <button
  style={styles.printBtn}
  onClick={(e) => { e.stopPropagation(); handlePrint(r); }}
>
  Print
</button>
                  <div style={styles.chevron}>
                    {expanded === r._id ? "▲" : "▼"}
                  </div>
                </div>

                {expanded === r._id && (
                  <div style={styles.cardBody}>
                    <div style={styles.detailRow}>
                      <span style={styles.detailLabel}>Doctor</span>
                      <span style={styles.detailValue}>{r.doctor?.name}</span>
                    </div>
                    <div style={styles.detailRow}>
                      <span style={styles.detailLabel}>Email</span>
                      <span style={styles.detailValue}>{r.doctor?.email}</span>
                    </div>
                    <div style={styles.detailRow}>
                      <span style={styles.detailLabel}>Visit date</span>
                      <span style={styles.detailValue}>
                        {new Date(r.visitDate).toLocaleString()}
                      </span>
                    </div>
                    <div style={styles.detailRow}>
                      <span style={styles.detailLabel}>Diagnosis</span>
                      <span style={styles.detailValue}>{r.diagnosis}</span>
                    </div>
                    {r.notes && (
                      <div style={styles.notesBox}>
                        <div style={styles.detailLabel}>Doctor notes</div>
                        <div style={styles.notesText}>{r.notes}</div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );

};
//----


const styles = {
  page: { backgroundColor: "#f0f2f5", minHeight: "100vh" },
  center: { textAlign: "center", marginTop: "80px", color: "#888" },
  container: { padding: "24px", maxWidth: "800px", margin: "0 auto" },
  header: { marginBottom: "24px" },
  title: { fontSize: "22px", fontWeight: "700", color: "#333", margin: 0 },
  sub: { fontSize: "14px", color: "#888", marginTop: "4px" },
  error: {
    backgroundColor: "#fdecea", color: "#c62828",
    padding: "12px", borderRadius: "8px",
    marginBottom: "16px", fontSize: "14px"
  },
  emptyState: {
    textAlign: "center", padding: "60px 20px",
    backgroundColor: "#fff", borderRadius: "12px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.07)"
  },
  emptyIcon: { fontSize: "40px", marginBottom: "12px" },
  emptyTitle: { fontSize: "16px", fontWeight: "600", color: "#333" },
  emptySub: { fontSize: "14px", color: "#999", marginTop: "6px" },
  list: { display: "flex", flexDirection: "column", gap: "12px" },
  card: {
    backgroundColor: "#fff", borderRadius: "12px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.07)", overflow: "hidden"
  },
  cardHeader: {
    display: "flex", justifyContent: "space-between",
    alignItems: "center", padding: "18px 20px", cursor: "pointer"
  },
  cardLeft: {},
  diagnosisLabel: {
    fontSize: "11px", fontWeight: "600",
    color: "#1a73e8", textTransform: "uppercase",
    letterSpacing: "0.05em", marginBottom: "4px"
  },
  diagnosis: { fontSize: "16px", fontWeight: "600", color: "#333" },
  meta: { fontSize: "13px", color: "#888", marginTop: "4px" },
  chevron: { color: "#aaa", fontSize: "12px" },
  cardBody: {
    borderTop: "1px solid #f0f0f0",
    padding: "16px 20px",
    backgroundColor: "#fafafa"
  },
  detailRow: {
    display: "flex", justifyContent: "space-between",
    padding: "8px 0", borderBottom: "1px solid #f0f0f0",
    fontSize: "14px"
  },
  detailLabel: { color: "#888", fontWeight: "500" },
  detailValue: { color: "#333", fontWeight: "500", textAlign: "right" },
  notesBox: {
    marginTop: "12px", padding: "12px",
    backgroundColor: "#fff8e1", borderRadius: "8px",
    borderLeft: "3px solid #f9a825"
  },
  notesText: { fontSize: "14px", color: "#555", marginTop: "6px", lineHeight: "1.6" },
  printBtn: {
  padding: "6px 12px", backgroundColor: "#e8f0fe",
  color: "#1a73e8", border: "none", borderRadius: "6px",
  fontSize: "12px", fontWeight: "600", cursor: "pointer"
}
};

export default MedicalRecords;